### ISSUE TITLE
🐞 Bug Report

### ISSUE THREAD

**Issue by TheRealToxicDev** [Izox-github/King-Tools-Hack#2]
### Specs

- 📜 King Tools Hack Version: 1.0.0
- 🔎 OS (or browser) version: Windows 10
- 🔑 Node.js version: 11
- 🏹 Complete "npm install / npm " output:

### 🕯️ Expected Behavior

Unknown

### 🧨 Actual Behavior

electron Error: [142:0317/121723.928276:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /rbd/pnpm-volume/c187cd94-66ca-4b81-ba61-33382c33ef97/node_modules/.registry.npmjs.org/electron/7.1.14/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755

### 🔥 How Do We Reproduce?

Run project on a host (IE: Glitch, Heroku, Digital Ocean ect)

### 🖼️ Extra (as an example of deposit to reproduce the problem, image, photo, link, etc.) 

N/A

**Comment by Izox-github** [comment]
Hello [TheRealToxicDev](https://github.com/TheRealToxicDev) 👋
🛠️ Apparently on your error, you have to run it as **root (admin)**.
⚒️ If that doesn't work, contact me on DISCORD: ! " 𝑰𝒁𝑶𝑿_#4004.
🏹 **INFO** : **I would make an executable (for those who are not experienced in computer science)**

**Comment by Izox-github** [comment]
✅ BUG SUCCESS : You have to run it as root (admin).
